import {
  Award,
  BriefcaseBusiness,
  CalendarClock,
  ClipboardCheck,
  FileBarChart,
  LayoutDashboard,
  MessageSquare,
  Package,
  PhoneCall,
  ShieldCheck,
  Target,
  Users,
} from "lucide-react";
import type { Role } from "@/lib/utils";

export const sidebarMenus: Record<Role, { label: string; href: string; icon: typeof LayoutDashboard }[]> = {
  ADMIN: [
    { label: "Dashboard", href: "/admin/dashboard", icon: LayoutDashboard },
    { label: "Leads", href: "/admin/leads", icon: Target },
    { label: "Customers", href: "/admin/customers", icon: BriefcaseBusiness },
    { label: "Tasks", href: "/admin/tasks", icon: ClipboardCheck },
    { label: "Follow-ups", href: "/admin/follow-ups", icon: CalendarClock },
    { label: "Products", href: "/admin/products", icon: Package },
    { label: "Communication", href: "/admin/notifications", icon: MessageSquare },
    { label: "Reports", href: "/admin/reports", icon: FileBarChart },
    { label: "Rewards", href: "/admin/rewards", icon: Award },
    { label: "Users", href: "/admin/users", icon: Users },
    { label: "Roles & Permissions", href: "/admin/permissions", icon: ShieldCheck },
  ],
  SUPERVISOR: [
    { label: "Dashboard", href: "/supervisor/dashboard", icon: LayoutDashboard },
    { label: "Leads", href: "/supervisor/leads", icon: Target },
    { label: "Customers", href: "/supervisor/customers", icon: BriefcaseBusiness },
    { label: "Tasks", href: "/supervisor/tasks", icon: ClipboardCheck },
    { label: "Follow-ups", href: "/supervisor/follow-ups", icon: CalendarClock },
    { label: "Communication", href: "/supervisor/communication", icon: MessageSquare },
    { label: "Products", href: "/supervisor/products", icon: Package },
    { label: "Rewards", href: "/supervisor/rewards", icon: Award },
    { label: "Reports", href: "/supervisor/reports", icon: FileBarChart },
  ],
  MARKETER: [
    { label: "Dashboard", href: "/marketer/dashboard", icon: LayoutDashboard },
    { label: "Leads", href: "/marketer/leads", icon: Target },
    { label: "Customers", href: "/marketer/customers", icon: BriefcaseBusiness },
    { label: "Tasks", href: "/marketer/tasks", icon: ClipboardCheck },
    { label: "Today's Plan", href: "/marketer/todays-plan", icon: CalendarClock },
    { label: "Communication", href: "/marketer/communication", icon: MessageSquare },
    { label: "Follow-ups", href: "/marketer/follow-ups", icon: PhoneCall },
    { label: "Products", href: "/marketer/products", icon: Package },
    { label: "Reports", href: "/marketer/reports", icon: FileBarChart },
    { label: "Rewards", href: "/marketer/rewards", icon: Award },
  ],
};
